language: php
php:
  - '7.0'
sudo: required
install:
  - pecl install ds
  - sudo echo 'extension=ds.so' > /etc/php/7.0/cli/conf.d/30-ds.ini
before_script:
  - composer install
script:
  - phpunit
cache:
  directories:
  - vendor
  files:
  - composer.lock
after_success:
  - bash <(curl -s https://codecov.io/bash)