language: php
php:
  - '7.0'
sudo: required
before_install: echo "extension=ds.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - pecl install ds
before_script:
  - composer install
script:
  - phpunit
cache:
  directories:
  - vendor
  files:
  - composer.lock
after_success:
  - bash <(curl -s https://codecov.io/bash)